<?php

namespace App\Constants;

class NewsletterConstants
{
    const EMAIL_ADS_STATUS_NOT_PROCESSED = 0;
    const EMAIL_ADS_STATUS_NOT_COLLECTED = 3;
    const EMAIL_ADS_STATUS_IN_PROCESS = 1;
    const EMAIL_ADS_STATUS_WAITING_TO_LIMIT = 4;
    const EMAIL_ADS_STATUS_COMPLETED = 2;


    const EMAIL_ADS_USER_STATUS_NOT_PROCESSED = 0;
    const EMAIL_ADS_USER_STATUS_BOUNCED = 2;
    const EMAIL_ADS_USER_STATUS_DELIVERED = 3;
    const EMAIL_ADS_USER_STATUS_OPENED = 4;
    const EMAIL_ADS_USER_STATUS_CLICKED = 5;
    const EMAIL_ADS_USER_STATUS_ORDERED = 6;
    const EMAIL_ADS_USER_STATUS_UNSUBSCRIBED = 7;


    const EMAIL_ADS_CLICKED_QUERY_PARAM = 'nlepowr';
    const EMAIL_ADS_UNSUBSCRIBE_QUERY_PARAM = 'unsepod';
}
