<?php

namespace App\Constants;

class ShippingConstants
{
    const ALTERNATIVE_SHIPPING_SELF_PICKUP = 'self_pickup';
    const ALTERNATIVE_SHIPPING_OTHER = 'other_shipping_method';

    const ALTERNATIVE_SHIPPING_METHODS = [
        '' => 'None',
        self::ALTERNATIVE_SHIPPING_SELF_PICKUP => 'Self pickup',
        self::ALTERNATIVE_SHIPPING_OTHER => 'Spedition / Freight Carrier',
    ];

    const DPD_TYPE = 1;
    const DHL_TYPE = 2;
    const TNT_TYPE = 4;
    const LOCAL_PICKUP_TYPE = 5;
    const OTHER = 6;

    const FREE_SHIPPING_REQUIREMENT = [
        'None' => 0,
        'Min order amount' => 1,
    ];

    const CARRIER = [
        'DPD' => self::DPD_TYPE,
        'DHL' => self::DHL_TYPE,
        'TNT' => self::TNT_TYPE,
        'LOCAL_PICKUP' => self::LOCAL_PICKUP_TYPE,
        'OTHER' => self::OTHER,
    ];

    const CARRIERS_PARCEL_URLS = [
        'DPD' => 'https://tracking.dpd.de/status/de_DE/parcel/',
        'DHL' => 'https://www.dhl.de/en/privatkunden/pakete-empfangen/verfolgen.html?piececode=',
        'TNT' => 'https://www.tnt.com/express/en_gc/site/shipping-tools/track.html?searchType=con&cons=',
    ];

    const SHIPPING_METHOD_TYPES = [
        0 => 'Free',
        1 => 'Flat rate',
    ];

    const SHIPPING_METHOD_TYPE_FREE = 'Free';
    const SHIPPING_METHOD_TYPE_FLAT_RATE = 'Flat rate';

    const SHIPPING_LABEL_SETTING_TYPES = [
        [
            'id' => self::DPD_TYPE,
            'name' => 'DPD shipping labels',
            'password' => 'test',
        ],
        [
            'id' => self::DHL_TYPE,
            'name' => 'DHL shipping labels',
            'password' => 'test',
        ],
        [
            'id' => self::TNT_TYPE,
            'name' => 'TNT shipping labels',
            'password' => 'test',
        ],
    ];

    const PDF_PAGE_SIZES = [
        self::DPD_TYPE => ['A4', 'A6'],
        self::DHL_TYPE => ['A4', '910-300-600', '910-300-610', '910-300-700', '910-300-700-oz', '910-300-710', '910-300-300',
            '910-300-300-oz', '910-300-400', '910-300-410', '100x70mm'],
        self::TNT_TYPE => [],
    ];

    const LABEL_START_POSITION = [
        'UPPER_LEFT' => 'Upper left',
        'UPPER_RIGHT' => 'Upper right',
        'LOWER_LEFT' => 'Lower left',
        'LOWER_RIGHT' => 'Lower right',
    ];

    const TERMS_OF_DELIVERY = [
        '01' => 'DAP customs cleared',
        '02' => 'DDP delivered customs cleared incl. duties excl. taxes',
        '03' => 'DDP delivered customs cleared incl. duties and taxes',
        '06' => 'DAP',
    ];

    const BOX_SIZES = [
        [
            'min_w' => 0,
            'max_w' => 3,
            'LENGTH' => 23,
            'HEIGHT' => 15.5,
            'WIDTH' => 11.5,
        ],
        [
            'min_w' => 3,
            'max_w' => 25,
            'LENGTH' => 32.5,
            'HEIGHT' => 21.5,
            'WIDTH' => 15,
        ],
        [
            'min_w' => 25,
            'max_w' => 999999,
            'LENGTH' => 35,
            'HEIGHT' => 20,
            'WIDTH' => 25,
        ]
    ];

    const TYPE_OF_EXPORTS = [
        'endgültig (Verkauf)' => 'endgültig (Verkauf)',
        'vorrübergehend (z.B. passive Veredelung)' => 'vorrübergehend (z.B. passive Veredelung)',
    ];

    const DEFAULT_INCOTERMS = [
        'DDP' => 'DDP',
        'DAP' => 'DAP',
    ];

    const COUNTRIES = [
        'AF' => 'Afghanistan',
        'AX' => 'Aland Islands',
        'AL' => 'Albania',
        'DZ' => 'Algeria',
        'AS' => 'American Samoa',
        'AD' => 'Andorra',
        'AO' => 'Angola',
        'AI' => 'Anguilla',
        'AQ' => 'Antarctica',
        'AG' => 'Antigua And Barbuda',
        'AR' => 'Argentina',
        'AM' => 'Armenia',
        'AW' => 'Aruba',
        'AU' => 'Australia',
        'AT' => 'Austria',
        'AZ' => 'Azerbaijan',
        'BS' => 'Bahamas',
        'BH' => 'Bahrain',
        'BD' => 'Bangladesh',
        'BB' => 'Barbados',
        'BY' => 'Belarus',
        'BE' => 'Belgium',
        'BZ' => 'Belize',
        'BJ' => 'Benin',
        'BM' => 'Bermuda',
        'BT' => 'Bhutan',
        'BO' => 'Bolivia',
        'BA' => 'Bosnia And Herzegovina',
        'BW' => 'Botswana',
        'BV' => 'Bouvet Island',
        'BR' => 'Brazil',
        'IO' => 'British Indian Ocean Territory',
        'BN' => 'Brunei Darussalam',
        'BG' => 'Bulgaria',
        'BF' => 'Burkina Faso',
        'BI' => 'Burundi',
        'KH' => 'Cambodia',
        'CM' => 'Cameroon',
        'CA' => 'Canada',
        'CV' => 'Cape Verde',
        'KY' => 'Cayman Islands',
        'CF' => 'Central African Republic',
        'TD' => 'Chad',
        'CL' => 'Chile',
        'CN' => 'China',
        'CX' => 'Christmas Island',
        'CC' => 'Cocos (Keeling) Islands',
        'CO' => 'Colombia',
        'KM' => 'Comoros',
        'CG' => 'Congo',
        'CD' => 'Congo, Democratic Republic',
        'CK' => 'Cook Islands',
        'CR' => 'Costa Rica',
        'CI' => 'Cote D\'Ivoire',
        'HR' => 'Croatia',
        'CU' => 'Cuba',
        'CY' => 'Cyprus',
        'CZ' => 'Czech Republic',
        'DK' => 'Denmark',
        'DJ' => 'Djibouti',
        'DM' => 'Dominica',
        'DO' => 'Dominican Republic',
        'EC' => 'Ecuador',
        'EG' => 'Egypt',
        'SV' => 'El Salvador',
        'GQ' => 'Equatorial Guinea',
        'ER' => 'Eritrea',
        'EE' => 'Estonia',
        'ET' => 'Ethiopia',
        'FK' => 'Falkland Islands (Malvinas)',
        'FO' => 'Faroe Islands',
        'FJ' => 'Fiji',
        'FI' => 'Finland',
        'FR' => 'France',
        'GF' => 'French Guiana',
        'PF' => 'French Polynesia',
        'TF' => 'French Southern Territories',
        'GA' => 'Gabon',
        'GM' => 'Gambia',
        'GE' => 'Georgia',
        'DE' => 'Germany',
        'GH' => 'Ghana',
        'GI' => 'Gibraltar',
        'GR' => 'Greece',
        'GL' => 'Greenland',
        'GD' => 'Grenada',
        'GP' => 'Guadeloupe',
        'GU' => 'Guam',
        'GT' => 'Guatemala',
        'GG' => 'Guernsey',
        'GN' => 'Guinea',
        'GW' => 'Guinea-Bissau',
        'GY' => 'Guyana',
        'HT' => 'Haiti',
        'HM' => 'Heard Island & Mcdonald Islands',
        'VA' => 'Holy See (Vatican City State)',
        'HN' => 'Honduras',
        'HK' => 'Hong Kong',
        'HU' => 'Hungary',
        'IS' => 'Iceland',
        'IN' => 'India',
        'ID' => 'Indonesia',
        'IR' => 'Iran, Islamic Republic Of',
        'IQ' => 'Iraq',
        'IE' => 'Ireland',
        'IM' => 'Isle Of Man',
        'IL' => 'Israel',
        'IT' => 'Italy',
        'JM' => 'Jamaica',
        'JP' => 'Japan',
        'JE' => 'Jersey',
        'JO' => 'Jordan',
        'KZ' => 'Kazakhstan',
        'KE' => 'Kenya',
        'KI' => 'Kiribati',
        'KR' => 'Korea',
        'KW' => 'Kuwait',
        'KG' => 'Kyrgyzstan',
        'LA' => 'Lao People\'s Democratic Republic',
        'LV' => 'Latvia',
        'LB' => 'Lebanon',
        'LS' => 'Lesotho',
        'LR' => 'Liberia',
        'LY' => 'Libyan Arab Jamahiriya',
        'LI' => 'Liechtenstein',
        'LT' => 'Lithuania',
        'LU' => 'Luxembourg',
        'MO' => 'Macao',
        'MK' => 'Macedonia',
        'MG' => 'Madagascar',
        'MW' => 'Malawi',
        'MY' => 'Malaysia',
        'MV' => 'Maldives',
        'ML' => 'Mali',
        'MT' => 'Malta',
        'MH' => 'Marshall Islands',
        'MQ' => 'Martinique',
        'MR' => 'Mauritania',
        'MU' => 'Mauritius',
        'YT' => 'Mayotte',
        'MX' => 'Mexico',
        'FM' => 'Micronesia, Federated States Of',
        'MD' => 'Moldova',
        'MC' => 'Monaco',
        'MN' => 'Mongolia',
        'ME' => 'Montenegro',
        'MS' => 'Montserrat',
        'MA' => 'Morocco',
        'MZ' => 'Mozambique',
        'MM' => 'Myanmar',
        'NA' => 'Namibia',
        'NR' => 'Nauru',
        'NP' => 'Nepal',
        'NL' => 'Netherlands',
        'AN' => 'Netherlands Antilles',
        'NC' => 'New Caledonia',
        'NZ' => 'New Zealand',
        'NI' => 'Nicaragua',
        'NE' => 'Niger',
        'NG' => 'Nigeria',
        'NU' => 'Niue',
        'NF' => 'Norfolk Island',
        'MP' => 'Northern Mariana Islands',
        'NO' => 'Norway',
        'OM' => 'Oman',
        'PK' => 'Pakistan',
        'PW' => 'Palau',
        'PS' => 'Palestinian Territory, Occupied',
        'PA' => 'Panama',
        'PG' => 'Papua New Guinea',
        'PY' => 'Paraguay',
        'PE' => 'Peru',
        'PH' => 'Philippines',
        'PN' => 'Pitcairn',
        'PL' => 'Poland',
        'PT' => 'Portugal',
        'PR' => 'Puerto Rico',
        'QA' => 'Qatar',
        'RE' => 'Reunion',
        'RO' => 'Romania',
        'RU' => 'Russian Federation',
        'RW' => 'Rwanda',
        'BL' => 'Saint Barthelemy',
        'SH' => 'Saint Helena',
        'KN' => 'Saint Kitts And Nevis',
        'LC' => 'Saint Lucia',
        'MF' => 'Saint Martin',
        'PM' => 'Saint Pierre And Miquelon',
        'VC' => 'Saint Vincent And Grenadines',
        'WS' => 'Samoa',
        'SM' => 'San Marino',
        'ST' => 'Sao Tome And Principe',
        'SA' => 'Saudi Arabia',
        'SN' => 'Senegal',
        'RS' => 'Serbia',
        'SC' => 'Seychelles',
        'SL' => 'Sierra Leone',
        'SG' => 'Singapore',
        'SK' => 'Slovakia',
        'SI' => 'Slovenia',
        'SB' => 'Solomon Islands',
        'SO' => 'Somalia',
        'ZA' => 'South Africa',
        'GS' => 'South Georgia And Sandwich Isl.',
        'ES' => 'Spain',
        'LK' => 'Sri Lanka',
        'SD' => 'Sudan',
        'SR' => 'Suriname',
        'SJ' => 'Svalbard And Jan Mayen',
        'SZ' => 'Swaziland',
        'SE' => 'Sweden',
        'CH' => 'Switzerland',
        'SY' => 'Syrian Arab Republic',
        'TW' => 'Taiwan',
        'TJ' => 'Tajikistan',
        'TZ' => 'Tanzania',
        'TH' => 'Thailand',
        'TL' => 'Timor-Leste',
        'TG' => 'Togo',
        'TK' => 'Tokelau',
        'TO' => 'Tonga',
        'TT' => 'Trinidad And Tobago',
        'TN' => 'Tunisia',
        'TR' => 'Turkey',
        'TM' => 'Turkmenistan',
        'TC' => 'Turks And Caicos Islands',
        'TV' => 'Tuvalu',
        'UG' => 'Uganda',
        'UA' => 'Ukraine',
        'AE' => 'United Arab Emirates',
        'GB' => 'United Kingdom',
        'US' => 'United States',
        'UM' => 'United States Outlying Islands',
        'UY' => 'Uruguay',
        'UZ' => 'Uzbekistan',
        'VU' => 'Vanuatu',
        'VE' => 'Venezuela',
        'VN' => 'Viet Nam',
        'VG' => 'Virgin Islands, British',
        'VI' => 'Virgin Islands, U.S.',
        'WF' => 'Wallis And Futuna',
        'EH' => 'Western Sahara',
        'YE' => 'Yemen',
        'ZM' => 'Zambia',
        'ZW' => 'Zimbabwe',
    ];

    const PREDICT_COUNTRIES = [
        'AT',
        'BE',
        'BG',
        'CH',
        'CZ',
        'DE',
        'DK',
        'EE',
        'FI',
        'FR',
        'GB',
        'GR',
        'HU',
        'IE',
        'LI',
        'LT',
        'LU',
        'LV',
        'MC',
        'NL',
        'NO',
        'PL',
        'PT',
        'RO',
        'SE',
        'SI',
        'SK',
        'SM',
        'US'
    ];

    const STORE_ORDER_MESSAGE = [
        'printOptions' => [
            'printOption' => [
                'paperFormat' => null,
                'outputFormat' => null,
                'startPosition' => null
            ]
        ],
        'order' => [
            'generalShipmentData' => [
                'sendingDepot' => null,
                'product' => null,
                'mpsCustomerReferenceNumber1' => null,
                'mpsCustomerReferenceNumber2' => null,
                'mpsWeight' => null,
                'sender' => [
                    'name1' => null,
                    'name2' => null,
                    'street' => null,
                    'houseNo' => null,
                    'state' => null,
                    'country' => null,
                    'zipCode' => null,
                    'city' => null,
                    'email' => null,
                    'phone' => null,
                    'gln' => null,
                    'contact' => null,
                    'fax' => null,
                    'customerNumber' => null,
                ],
                'recipient' => [
                    'name1' => null,
                    'name2' => null,
                    'street' => null,
                    'houseNo' => null,
                    'state' => null,
                    'country' => null,
                    'gln' => null,
                    'zipCode' => null,
                    'customerNumber' => null,
                    'contact' => null,
                    'phone' => null,
                    'fax' => null,
                    'email' => null,
                    'city' => null,
                    'comment' => null
                ]
            ],
            'parcels' => [],
            'productAndServiceData' => [
                'saturdayDelivery' => false,
                'orderType' => 'consignment',
                'pickup' => null
            ]
        ]
    ];

}
