<?php

namespace App\Constants;

class UploadConstant
{
    const STATUSES = [
        'In process' => 1,
        'Failed' => 2,
        'Completed' => 3,
    ];

    const TYPES = [
        'Categories' => 1,
        'Users' => 2,
        'Reviews' => 3,
        'Attributes' => 4,
        'Attributes values' => 5,
        'Coupons' => 6,
        'Products' => 7,
        'Menus' => 8,
        'Translations' => 9,
        'Items' => 10,
        'Bank transfer processing' => 11,
        'Media' => 12,
        'Pages' => 13,
        'Posts' => 14,
        'Shipping costs' => 15
    ];

    const CATEGORIES_FILE_HEADERS = [
        'id' => 'ID',
        'parent_id' => 'Parent ID',
        'products_showing_type' => 'Showing type (Link|Add to cart|With popup|Variables with variations)',
        'media_id' => 'Base image media ID or URL',
        'desktop' => 'Products per row desktop',
        'tablet' => 'Products per row tablet',
        'mobile' => 'Products per row mobile',
        'price_adjustment' => 'Price adjustment',
        'language_code' => 'Language code',
        'related_category_translation_id' => 'Related category ID',
        'name' => 'Name',
        'slug' => 'Slug',
        'description' => 'Description',
        'meta_title' => 'Meta title',
        'meta_keywords' => 'Meta keywords',
        'meta_description' => 'Meta description',
    ];

    const ITEMS_FILE_HEADERS = [
        'sku' => 'SKU',
        'category_id' => 'Category ID',
        'name' => 'Name',
        'production_price' => 'Production price',
        'regular_price' => 'Regular price',
        'stock_quantity' => 'Stock quantity',
        'negative_stock' => 'Allow negative stock (Yes|No)',
        'net_weight' => 'Net weight',
        'gross_weight' => 'Gross weight',
        'position_packstation' => 'Position packstation',
        'country' => 'Country',
        'hs_code' => 'hs_code',
        'hs_name' => 'hs_name',
        'proper_shipping_name' => 'Proper shipping name',
        'un_numbers' => 'un_numbers',
        'package_group' => 'package_group',
        'dangerous_goods_class' => 'dangerous_goods_class',
        'mark_nos' => 'mark_nos',
        'packages_type' => 'package_type',
        'stock_status' => 'Stock status (in_stock|out_of_stock)',
        'status' => 'Status (Active|Inactive)',
    ];

    const USERS_FILE_HEADERS = [
        'id' => 'ID',
        'user_group' => 'User group',
        'name' => 'Name',
        'last_name' => 'Last name',
        'email' => 'Email',
        'gtin' => 'GTIN',
        'password' => 'Password',
        'wc_password' => 'WC password (token)',
        'newsletter_subscribed' => 'Is newsletter subscribed (Yes|No)',
        'billing_address_country' => 'Billing: country',
        'billing_address_name' => 'Billing: name',
        'billing_address_last_name' => 'Billing: last name',
        'billing_address_company' => 'Billing: company',
        'billing_address_address' => 'Billing: address',
        'billing_address_address_2' => 'Billing: address 2',
        'billing_address_city' => 'Billing: city',
        'billing_address_zip' => 'Billing: zip',
        'billing_address_state' => 'Billing: state',
        'billing_address_phone' => 'Billing: phone',
        'billing_address_email' => 'Billing: email',
        'billing_address_vat_number' => 'Billing: vat_number',
        'shipping_address_country' => 'Shipping: country',
        'shipping_address_name' => 'Shipping: name',
        'shipping_address_last_name' => 'Shipping: last name',
        'shipping_address_company' => 'Shipping: company',
        'shipping_address_address' => 'Shipping: address',
        'shipping_address_address_2' => 'Shipping: address 2',
        'shipping_address_city' => 'Shipping: city',
        'shipping_address_zip' => 'Shipping: zip',
        'shipping_address_state' => 'Shipping: state',
    ];

    const REVIEWS_FILE_HEADERS = [
        'id' => 'ID',
        'user_Id' => 'User ID',
        'product_sku' => 'Product SKU',
        'name' => 'Name',
        'email' => 'Email',
        'rating' => 'Rating',
        'status' => 'Status (Active|Inactive)',
        'attachment' => 'Attachment: file urls',
        'country_code' => 'Country code',
        'text' => 'Text',
        'date' => 'Date',
    ];

    const ATTRIBUTE_TYPES_FILE_HEADERS = [
        'id' => 'ID',
        'default_sort_order' => 'Default sort order (id|value|priority)',
        'type' => 'Type (dropdown|radio)',
        'logic' => 'Logic (variation|simple)',
        'language_code' => 'Language code',
        'name' => 'Name',
        'label' => 'Label',
        'slug' => 'Slug',
    ];

    const PAGES_FILE_HEADERS = [
        'id' => 'ID',
        'language_code' => 'Language code',
        'name' => 'Name (Read only)',
        'slug' => 'Slug',
        'meta_title' => 'Meta Title',
        'meta_keywords' => 'Meta Keywords',
        'meta_description' => 'Meta Description',
        'path' => 'Path (Read only)',
    ];

    const ATTRIBUTE_FILE_HEADERS = [
        'id' => 'ID',
        'media_id' => 'Media ID or URL',
        'attribute_type_id' => 'Attribute ID',
        'priority' => 'Priority',
        'language_code' => 'Language code',
        'value' => 'Value',
        'slug' => 'Slug',
        'description' => 'Description'
    ];

    const COUPONS_FILE_HEADERS = [
        'id' => 'ID',
        'code' => 'Code',
        'type' => 'Type (Fixed cart discount|Percentage discount)',
        'amount' => 'Amount',
        'expires_at' => 'Expires date (Format: D.M.Y)',
        'min_spend' => 'Min spend',
        'max_spend' => 'Max spend',
        'exclude_sale_items' => 'Exclude sale items (Yes|No)',
        'usage_limit' => 'Usage limit per coupon',
        'usage_limit_per_user' => 'Usage limit per user',
        'description' => 'Description',
        'free_shipping' => 'Free shipping (Yes|No)',
        'status' => 'Status (Active|Inactive)',
        'product_ids' => 'Product IDs',
        'excluded_product_ids' => 'Excluded product IDs',
        'category_ids' => 'Category IDs',
        'excluded_category_ids' => 'Excluded category IDs',
        'allowed_emails' => 'Allowed Emails (Example: test@example.com|test1@example.com)',
    ];

    const PRODUCTS_FILE_HEADERS = [
        'sku' => 'SKU',
        'gtin' => 'GTIN',
        'parents' => "Item's skus",
        'watermark_media' => 'Watermark Media ID or URL',
        'media_id' => 'Media ID or URL',
        'type' => 'Type (simple|variable|bundle|gift_card)',
        'stock_status' => 'Stock status (in_stock|out_of_stock)',
        'base_price' => 'Base price',
        'regular_price' => 'Regular price',
        'sales_price' => "Sale's price",
        'tax_status' => 'Tax status (Taxable|None)',
        'enable_reviews' => 'Reviews access (Enabled|Disabled)',
        'extra_product' => 'Is extra (Yes|No)',
        'variants_export_into_feed' => 'Variants export into feed (Yes|No)',
        'new' => 'Is new (Yes|No)',
        'bestseller' => 'Is bestseller (Yes|No)',
        'status' => 'Status (Active|Inactive)',
        'variable_attribute_ids' => 'Variable attribute IDs',
        'simple_attribute_ids' => 'Simple attribute IDs',
        'category_ids' => 'Category IDs',
        'upsells_product_ids' => 'Upsells SKUs',
        'cross_sells_product_ids' => 'Cross sells SKUs',
        'related_product_ids' => 'Related SKUs',
        'related_reviewer_id' => 'Related reviewer product SKU',
        'extra_products_product_ids' => 'Extra products SKUs',
        'calculator_id' => 'Calculator ID',
        'gallery_ids' => 'Gallery media IDs or URLs',
        'priority' => 'Priority',
        'hs_code' => 'HS code',
        'reel_ids' => 'Reels media IDs or URLs',
        'shorts_urls' => 'Shorts URLs',
        'delete_product' => 'Delete full product (Write "delete" if need delete)',
        'language_code' => 'Language code',
        'slug' => 'Slug',
        'name' => 'Name',
        'sub_name' => 'Sub name',
        'short_description' => 'Short description',
        'description' => 'Description',
        'watermark_media_translation' => 'Watermark Media ID or URL translated',
        'media_id_translation' => 'Media ID or URL translated',
        'gallery_ids_translation' => 'Gallery media IDs or URLs translated',
        'meta_title' => 'Meta Title',
        'meta_keywords' => 'Meta Keywords',
        'meta_description' => 'Meta Description',
        'snippet_id' => 'Snippet ID',
        'a_plus_content_id' => 'A + content ID',
        'sec_a_plus_content_id' => 'Second A + content ID',
        'translation_status' => 'Translation status (Active|Inactive)',
        'reel_ids_translation' => 'Reels media IDs or URLs translated',
        'shorts_urls_translation' => 'Shorts URLs translated',
        'delete_translation' => 'Delete translation (Write "delete" if need delete)',
    ];

    const PRODUCT_VARIATIONS_FILE_HEADERS = [
        'id' => 'Variant ID (Read only)',
        'product_name' => 'Product (Read only)',
        'product_id' => 'Product ID',
        'attribute_value_1' => 'Attribute value 1 (Read only)',
        'attribute_value_2' => 'Attribute value 2 (Read only)',
        'attribute_value_3' => 'Attribute value 3 (Read only)',
        'attribute_value_4' => 'Attribute value 4 (Read only)',
        'sku' => 'SKU',
        'parent_skus' => "Item's SKUs",
        'stock_status' => 'Stock status (in_stock|out_of_stock)',
        'base_price' => 'Base price',
        'regular_price' => 'Regular price',
        'sales_price' => "Sale's price",
        'tax_status' => 'Tax status (Taxable|None)',
        'status' => 'Status (Active|Inactive)',
        'media_id' => 'Media ID or URL',
        'gallery_ids' => 'Gallery media IDs or URLs',
        'delete_product' => 'Delete full product (Write "delete" if need delete)',
        'language_code' => 'Language code',
        'name' => 'Name',
        'short_description' => 'Short description',
        'description' => 'Description',
        'media_id_translation' => 'Media ID or URL translated',
        'gallery_ids_translation' => 'Gallery media IDs or URLs translated',
        'size_by_unit' => 'Size by unit',
        'unit' => 'Unit',
        'is_invalid' => 'Is invalid (Read only)',
        'delete_translation' => 'Delete translation (Write "delete" if need delete)',
    ];

    const MENUS_FILE_HEADERS = [
        'id' => 'ID',
        'type' => 'Type (HeaderTop|HeaderBottom|FooterInformation|FooterAccess)',
        'parent_id' => 'Parent ID',
        'category_translation_id' => 'Related category ID',
        'product_translation_id' => 'Related product ID',
        'page_translation_id' => 'Related page ID',
        'post_translation_id' => 'Related post ID',
        'new_tab' => 'Open on new tab (Yes|No)',
        'status' => 'Status (Active|Inactive)',
        'language_code' => 'Language code',
        'name' => 'Name',
        'url' => 'URL'
    ];

    const MEDIA_FILE_HEADERS = [
        'id' => 'ID',
        'url' => 'URL (Read only)',
        'language_code' => 'Language code',
        'alt' => 'alt',
    ];

    const TRANSLATIONS_FILE_HEADERS = [
        'key' => 'Key (Read only)',
        'base_language' => 'Base language (Read only)',
        'language_code' => 'Language code',
        'value' => 'Value',
    ];
}
